### ISSUE TITLE
Bug: Migrate mapstructure to maintained fork

### ISSUE THREAD

**Issue by niklastreml** [caas-team/sparrow#172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We're currently using mapstructure, which has been [archived on 22.07.2024](https://gist.github.com/mitchellh/90029601268e59a29e64e55bab1c5bdc). We'll have to migrate to a maintained fork. [This one](https://github.com/go-viper/mapstructure) seems to be the one recommended one and is also the one [used by viper](https://github.com/spf13/viper/blob/master/go.mod#L7)

### Steps To Reproduce

[Migration Guide](https://github.com/go-viper/mapstructure?tab=readme-ov-file#migrating-from-githubcommitchellhmapstructure)

### Who can address the issue?

Anyone really, should only take a few minutes

### Anything else?

https://github.com/go-viper/mapstructure?tab=readme-ov-file#migrating-from-githubcommitchellhmapstructure
https://github.com/mitchellh/mapstructure
https://gist.github.com/mitchellh/90029601268e59a29e64e55bab1c5bdc

**Comment by lvlcn-t** [comment]
I've already done this in the PR #153 as it's only an indirect dependency of viper and they removed it with their new version.
