### ISSUE TITLE
Feature: Expose Checks Result as Prometheus Metrics

### ISSUE THREAD

**Issue by y-eight** [caas-team/sparrow#32]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Problem Description

Currently, the check results are exposed by a RESTful API in JSON format. The data should be exposed as metrics as well.

### Solution Description

Results gathered by the checks should be exposed as Prometheus metrics.

The check itself should set the metrics.

**Comment by NiklasTreml** [comment]
Can this be closed since https://github.com/caas-team/sparrow/pull/45 was merged?
