### ISSUE TITLE
Match up Health & Latency Checks 

### ISSUE THREAD

**Issue by y-eight** [caas-team/sparrow#33]
# Problem Description

Currently, the two checks (health and latency) have been designed separately from each other. The functionality is similar. The checks architecture should be similar.

Additionally, the latency check should use time references in exposed API keys e.g. if the interval is defined in seconds; use intervalSec: 1.

# Solution

The checks should be matched up so that functionality and code readability is more clear and easier.

**Comment by lvlcn-t** [comment]
The following discussion from #29 should be addressed:

- @y-eight addressed in a [discussion](https://github.com/caas-team/sparrow/pull/29#discussion_r1419592664)
  
  > Result.Err is a string because it is directly exposed by the Api.
  > 
  > Currently it is not used. We should consider using it when something in general is not working for the check (like in the registration part). We should not forget about this but should be part of #33.
