### ISSUE TITLE
Enhance Health Check Configuration

### ISSUE THREAD

**Issue by y-eight** [caas-team/sparrow#34]
### Problem Description

The latency check is configurable for several parameters like the interval. The health check should be configurable as well.

### Solution

The following parameters should be configurable:

- interval the check should run
- the http timeout
- the retry count
- the initial retry delay

The implementation can be done similar to the latency check

**Comment by lvlcn-t** [comment]
@y-eight I'd do this issue as part of #33 because I think this should be part of harmonizing the checks.
