### ISSUE TITLE
Feature: Grafana Dashboards

### ISSUE THREAD

**Issue by niklastreml** [caas-team/sparrow#70]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Problem Description

#69 introduces serviceMonitors to the helm chart. How about we also provide grafana dashboards, that go along with the service monitors. We could use the dashboard that the SRE team provides as a baseline. We should only work on this once the prometheus metrics are semi stabilized, otherwise we waste a lot of time on maintaining the dashboards.

### Who can address the issue?

Anyone willing to spend some time in grafana writing promql queries

**Comment by puffitos** [comment]
I have some standard dashboards which were used for our demo, I can bundle them up in the helm chart.
