### ISSUE TITLE
Bug: Viper BindStruct hidden behind feature flag in viper >=v1.18.0

### ISSUE THREAD

**Issue by niklastreml** [caas-team/sparrow#78]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We need to be careful when updating viper beyond v1.18.0

https://github.com/caas-team/sparrow/pull/73#issuecomment-1898997271

We should write a test case that checks whether marshalling from env variables works properly everywhere, so that we notice when someone updates the library and breaks it.

### Expected Behavior

To fix this, we need to update our build and test pipelines to include the feature flag `-tags=viper_bind_struct`

### Who can address the issue?

Anyone

**Comment by lvlcn-t** [comment]
The build constraint can be removed as soon as https://github.com/spf13/viper/pull/1854 made it into a new release.
