### ISSUE TITLE
Check Config (and RuntimeConfig) Validation 

### ISSUE THREAD

**Issue by puffitos** [caas-team/sparrow#97]
@puffitos Can you create an issue to the validation part you've mentioned in your PR?

_Originally posted by @lvlcn-t in https://github.com/caas-team/sparrow/issues/93#issuecomment-1916988810_
            
## Issue

The checks.Runtime Interface should also have a Validate method to validate the configuration per check. 

## Motivation

The Validate can then trickle up to the runtime.Config struct, which should have a validate Method to validate all configurations. This will ensure only valid configurations are passed to the running checks and should add to the robustness of the sparrow.

**Comment by lvlcn-t** [comment]
@puffitos 
I'd rather see it as part of the `checks.Runtime` interface so every check can implement their own validation.
